# Generated by Django 5.0.3 on 2024-03-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.IntegerField()),
                ('weekly', models.IntegerField()),
                ('monthly', models.IntegerField()),
                ('yearly', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HabitFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity', models.CharField(max_length=100)),
                ('number_of_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HabitPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HabitTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habitsApi.habitfrequency')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habitsApi.habitperiod')),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habitsApi.habittimer')),
            ],
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('done', models.BooleanField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habitsApi.habit')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='habitsApi.user')),
            ],
        ),
        migrations.AddField(
            model_name='habit',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habitsApi.workspace'),
        ),
    ]
